export default {
    LOAD_DETAILED_DONATION: 'LOAD_DETAILED_DONATION',
    LOAD_DONATIONS: 'LOAD_DONATIONS',

    LOAD_DETAILED_CHARITY: 'LOAD_DETAILED_CHARITY',
    LOAD_CHARITIES: 'LOAD_CHARITIES'
};
